"""
Resume Scorer Report Generator
Generates PDF and Markdown summary reports for candidate download.
"""

import io
from typing import Dict, Any

def generate_markdown_report(analysis_results: Dict[str, Any]) -> str:
    """Generates a structured markdown audit report."""
    res = analysis_results
    breakdown = res["scores_breakdown"]
    skills = res["skills_summary"]
    impact = res["impact_analysis"]
    readability = res["readability"]
    contact = res["contact_info"]

    md = f"""# 📄 AI/ML Resume Scorer & Analytics Audit Report

**Target Role / Benchmark:** {res['target_role']}  
**Overall Composite Score:** {res['composite_score']} / 100  
**Verdict:** {res['verdict']}  
**Assessment Summary:** {res['verdict_desc']}

---

## 📊 Score Breakdown
- **Core AI/ML Hard Skills:** {breakdown['hard_skill_score']}%
- **TF-IDF Semantic Similarity:** {breakdown['semantic_score']}%
- **Quantifiable Impact & Action Verbs:** {breakdown['impact_score']}%
- **MLOps & Production Readiness:** {breakdown['mlops_score']}%
- **ATS Formatting & Structure Health:** {breakdown['ats_health_score']}%

---

## 👤 Candidate Contact & Profile
- **Email:** {contact.get('email') or '❌ Missing'}
- **Phone:** {contact.get('phone') or '❌ Missing'}
- **LinkedIn:** {contact.get('linkedin') or '❌ Missing'}
- **GitHub:** {contact.get('github') or '❌ Missing'}
- **Portfolio / Website:** {contact.get('portfolio') or '❌ Missing'}

---

## 🎯 Skill Alignment & Gap Analysis

### ✅ Matched Core Skills ({len(skills['matched_core'])})
{', '.join(skills['matched_core']) if skills['matched_core'] else 'None detected'}

### ❌ Missing Core Skills ({len(skills['missing_core'])})
{', '.join(skills['missing_core']) if skills['missing_core'] else 'None - Full Core Match!'}

### ⚡ Matched Secondary Skills ({len(skills['matched_secondary'])})
{', '.join(skills['matched_secondary']) if skills['matched_secondary'] else 'None detected'}

### ➕ Bonus / Distinct Skills ({len(skills['bonus_skills'])})
{', '.join(skills['bonus_skills']) if skills['bonus_skills'] else 'None'}

---

## 💡 Impact & Action Verb Analytics
- **Strong Action Verbs Found:** {', '.join(impact['strong_verbs_found']) if impact['strong_verbs_found'] else 'None detected'}
- **Weak / Passive Phrases Detected:** {', '.join(impact['weak_phrases_found']) if impact['weak_phrases_found'] else 'None (Clean)'}
- **Quantifiable Metrics Detected:** {', '.join(impact['metrics_found']) if impact['metrics_found'] else 'None detected'}
- **Strong Bullets (X-Y-Z Formula):** {impact['strong_bullets_count']} / {impact['total_bullets_analyzed']}

---

## 📚 Priority Learning Roadmap
"""
    for rec in res["learning_recommendations"]:
        md += f"- **[{rec['priority']}] {rec['skill'].title()}**: [{rec['title']}]({rec['link']})\n"

    md += f"""
---
## 📑 Document Readability
- **Word Count:** {readability['word_count']} words ({readability['length_status']})
- **Flesch Reading Ease:** {readability['flesch_score']} ({readability['readability_status']})

*Report generated by AI/ML Resume Scorer & Analytics Engine.*
"""
    return md


def generate_pdf_report(analysis_results: Dict[str, Any]) -> bytes:
    """Generates a professional PDF audit report using ReportLab."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )
        
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#1E293B'),
            spaceAfter=6
        )
        subtitle_style = ParagraphStyle(
            'SubTitleStyle',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#64748B'),
            spaceAfter=12
        )
        heading_style = ParagraphStyle(
            'HeadingStyle',
            parent=styles['Heading2'],
            fontSize=12,
            leading=16,
            textColor=colors.HexColor('#0F172A'),
            spaceBefore=10,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'BodyStyle',
            parent=styles['Normal'],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor('#334155')
        )
        badge_style = ParagraphStyle(
            'BadgeStyle',
            parent=styles['Normal'],
            fontSize=13,
            leading=16,
            textColor=colors.HexColor('#059669'),
            alignment=1
        )

        elements = []
        res = analysis_results
        breakdown = res["scores_breakdown"]
        skills = res["skills_summary"]
        impact = res["impact_analysis"]
        contact = res["contact_info"]

        # Title
        elements.append(Paragraph("<b>AI/ML RESUME AUDIT & ATS SCORER REPORT</b>", title_style))
        elements.append(Paragraph(f"Target Benchmark: <b>{res['target_role']}</b>", subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#3B82F6'), spaceAfter=10))

        # Overall Score Box
        score_data = [
            [
                Paragraph(f"<b>Overall Score</b><br/><font size=24 color='#2563EB'><b>{res['composite_score']}%</b></font>", badge_style),
                Paragraph(f"<b>Assessment Verdict</b><br/><b>{res['verdict']}</b><br/><font size=8 color='#475569'>{res['verdict_desc']}</font>", body_style)
            ]
        ]
        score_table = Table(score_data, colWidths=[140, 390])
        score_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#E2E8F0')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(score_table)
        elements.append(Spacer(1, 10))

        # Breakdown Table
        elements.append(Paragraph("<b>1. Multi-Dimensional Score Breakdown</b>", heading_style))
        breakdown_data = [
            ["Dimension", "Score", "Evaluation Metric"],
            ["Core AI/ML Skills", f"{breakdown['hard_skill_score']}%", "Direct keyword phrase matching for required tools"],
            ["TF-IDF Semantic Fit", f"{breakdown['semantic_score']}%", "Mathematical contextual vector similarity"],
            ["Quantifiable Impact", f"{breakdown['impact_score']}%", "Action verbs and quantified metrics (%, $, scale)"],
            ["MLOps & Infrastructure", f"{breakdown['mlops_score']}%", "Deployment, Docker, pipelines, and monitoring tools"],
            ["ATS Health & Readability", f"{breakdown['ats_health_score']}%", "Flesch reading ease, structure & contact details"]
        ]
        breakdown_table = Table(breakdown_data, colWidths=[150, 60, 320])
        breakdown_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ]))
        elements.append(breakdown_table)
        elements.append(Spacer(1, 10))

        # Skills Summary
        elements.append(Paragraph("<b>2. Key Competencies & Skill Gaps</b>", heading_style))
        matched_str = ", ".join(skills["matched_core"]) if skills["matched_core"] else "None detected"
        missing_str = ", ".join(skills["missing_core"]) if skills["missing_core"] else "Full Core Alignment!"
        bonus_str = ", ".join(skills["bonus_skills"][:10]) if skills["bonus_skills"] else "None"

        skills_table_data = [
            [Paragraph("<b>Matched Core Skills:</b>", body_style), Paragraph(f"<font color='#059669'>{matched_str}</font>", body_style)],
            [Paragraph("<b>Missing Critical Skills:</b>", body_style), Paragraph(f"<font color='#DC2626'>{missing_str}</font>", body_style)],
            [Paragraph("<b>Bonus Skills:</b>", body_style), Paragraph(bonus_str, body_style)]
        ]
        skills_table = Table(skills_table_data, colWidths=[150, 380])
        skills_table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F8FAFC')),
            ('PADDING', (0, 0), (-1, -1), 5),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        elements.append(skills_table)
        elements.append(Spacer(1, 10))

        # Bullet Impact
        elements.append(Paragraph("<b>3. Recruiter Bullet Point & Impact Review</b>", heading_style))
        verbs_str = ", ".join(impact["strong_verbs_found"][:10]) if impact["strong_verbs_found"] else "None"
        metrics_str = ", ".join(impact["metrics_found"][:8]) if impact["metrics_found"] else "None"
        
        impact_table_data = [
            [Paragraph("<b>Strong Verbs Found:</b>", body_style), Paragraph(verbs_str, body_style)],
            [Paragraph("<b>Quantified Metrics:</b>", body_style), Paragraph(metrics_str, body_style)],
            [Paragraph("<b>X-Y-Z Strong Bullets:</b>", body_style), Paragraph(f"{impact['strong_bullets_count']} of {impact['total_bullets_analyzed']} analyzed", body_style)]
        ]
        impact_table = Table(impact_table_data, colWidths=[150, 380])
        impact_table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F8FAFC')),
            ('PADDING', (0, 0), (-1, -1), 5),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        elements.append(impact_table)
        elements.append(Spacer(1, 10))

        # Recommendations
        elements.append(Paragraph("<b>4. Recommended Action Steps</b>", heading_style))
        rec_items = []
        for rec in res["learning_recommendations"][:5]:
            rec_items.append([
                Paragraph(f"<b>[{rec['priority'].split()[0]}] {rec['skill'].title()}</b>", body_style),
                Paragraph(f"{rec['title']}", body_style)
            ])
        if rec_items:
            rec_table = Table(rec_items, colWidths=[160, 370])
            rec_table.setStyle(TableStyle([
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F8FAFC')),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(rec_table)

        doc.build(elements)
        return buffer.getvalue()
    except Exception as e:
        # Fallback to plain bytes text if reportlab fails
        return f"PDF Generation Error: {str(e)}".encode("utf-8")
